"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChatModelFactory = void 0;
var base_1 = require("./base");
var you_1 = require("./you");
var mcbbs_1 = require("./mcbbs");
var phind_1 = require("./phind");
var forefront_1 = require("./forefront");
var vita_1 = require("./vita");
var skailar_1 = require("./skailar");
var fakeopen_1 = require("./fakeopen");
var easychat_1 = require("./easychat");
var better_1 = require("./better");
var pweb_1 = require("./pweb");
var bai_1 = require("./bai");
var gra_1 = require("./gra");
var magic_1 = require("./magic");
var chim_1 = require("./chim");
var ram_1 = require("./ram");
var chur_1 = require("./chur");
var xun_1 = require("./xun");
var vvm_1 = require("./vvm");
var claude_1 = require("./claude");
var cursor_1 = require("./cursor");
var auto_1 = require("./auto");
var chatbase_1 = require("./chatbase");
var ails_1 = require("./ails");
var chatdemo_1 = require("./chatdemo");
var sincode_1 = require("./sincode");
var openai_1 = require("./openai");
var oneapi_1 = require("./oneapi");
var jasper_1 = require("./jasper");
var acytoo_1 = require("./acytoo");
var google_1 = require("./google");
var www_1 = require("./www");
var ddg_1 = require("./ddg");
var ChatModelFactory = /** @class */ (function () {
    function ChatModelFactory(options) {
        this.modelMap = new Map();
        this.options = options;
        this.init();
    }
    ChatModelFactory.prototype.init = function () {
        // register new model here
        this.modelMap.set(base_1.Site.You, new you_1.You({ name: base_1.Site.You }));
        this.modelMap.set(base_1.Site.Phind, new phind_1.Phind({ name: base_1.Site.Phind }));
        this.modelMap.set(base_1.Site.Forefront, new forefront_1.Forefrontnew({ name: base_1.Site.Forefront, net: false }));
        this.modelMap.set(base_1.Site.Mcbbs, new mcbbs_1.Mcbbs({ name: base_1.Site.Mcbbs }));
        this.modelMap.set(base_1.Site.ChatDemo, new chatdemo_1.ChatDemo({ name: base_1.Site.ChatDemo }));
        this.modelMap.set(base_1.Site.Vita, new vita_1.Vita({ name: base_1.Site.Vita }));
        this.modelMap.set(base_1.Site.Skailar, new skailar_1.Skailar({ name: base_1.Site.Skailar }));
        this.modelMap.set(base_1.Site.FakeOpen, new fakeopen_1.FakeOpen({ name: base_1.Site.FakeOpen }));
        this.modelMap.set(base_1.Site.EasyChat, new easychat_1.EasyChat({ name: base_1.Site.EasyChat, model: base_1.ModelType.GPT4 }));
        this.modelMap.set(base_1.Site.Better, new better_1.Better({ name: base_1.Site.Better }));
        this.modelMap.set(base_1.Site.PWeb, new pweb_1.PWeb({ name: base_1.Site.PWeb }));
        this.modelMap.set(base_1.Site.Bai, new bai_1.Bai({ name: base_1.Site.Bai }));
        this.modelMap.set(base_1.Site.Gra, new gra_1.Gra({ name: base_1.Site.Gra }));
        this.modelMap.set(base_1.Site.Magic, new magic_1.Magic({ name: base_1.Site.Magic }));
        this.modelMap.set(base_1.Site.Chim, new chim_1.Chim({ name: base_1.Site.Chim }));
        this.modelMap.set(base_1.Site.Ram, new ram_1.Ram({ name: base_1.Site.Ram }));
        this.modelMap.set(base_1.Site.Chur, new chur_1.Chur({ name: base_1.Site.Chur }));
        this.modelMap.set(base_1.Site.Xun, new xun_1.Xun({ name: base_1.Site.Xun }));
        this.modelMap.set(base_1.Site.VVM, new vvm_1.VVM({ name: base_1.Site.VVM }));
        this.modelMap.set(base_1.Site.Claude, new claude_1.Claude({ name: base_1.Site.Claude }));
        this.modelMap.set(base_1.Site.Cursor, new cursor_1.Cursor({ name: base_1.Site.Cursor }));
        this.modelMap.set(base_1.Site.OneAPI, new oneapi_1.OneAPI({ name: base_1.Site.OneAPI }));
        this.modelMap.set(base_1.Site.Auto, new auto_1.Auto({ name: base_1.Site.Auto, ModelMap: this.modelMap }));
        this.modelMap.set(base_1.Site.ChatBase, new chatbase_1.ChatBase({ name: base_1.Site.ChatBase }));
        this.modelMap.set(base_1.Site.AiLs, new ails_1.AILS({ name: base_1.Site.AiLs }));
        this.modelMap.set(base_1.Site.SinCode, new sincode_1.SinCode({ name: base_1.Site.SinCode }));
        this.modelMap.set(base_1.Site.OpenAI, new openai_1.OpenAI({ name: base_1.Site.OpenAI }));
        this.modelMap.set(base_1.Site.Jasper, new jasper_1.Jasper({ name: base_1.Site.Jasper }));
        this.modelMap.set(base_1.Site.AcyToo, new acytoo_1.AcyToo({ name: base_1.Site.AcyToo }));
        this.modelMap.set(base_1.Site.Google, new google_1.Google({ name: base_1.Site.Google }));
        this.modelMap.set(base_1.Site.WWW, new www_1.WWW({ name: base_1.Site.WWW }));
        this.modelMap.set(base_1.Site.DDG, new ddg_1.DDG({ name: base_1.Site.DDG }));
    };
    ChatModelFactory.prototype.get = function (model) {
        return this.modelMap.get(model);
    };
    return ChatModelFactory;
}());
exports.ChatModelFactory = ChatModelFactory;
